(function () {
    try {
        var _head = document.querySelector('head');

        // 1. gpt.js 로더 스크립트
        var _script = document.createElement('script');
        _script.src = 'https://securepubads.g.doubleclick.net/tag/js/gpt.js';
        _script.async = true;
        _head.appendChild(_script);

        // 2. 설정 로직을 텍스트로 담은 인라인 스크립트
        var _inline = document.createElement('script');
        _inline.innerHTML = [
            "window.googletag = window.googletag || { cmd: [] };",
            "googletag.cmd.push(function () {",
            "    var _anchFlag = false;",
            "    var _uiUp = false;",
            "    googletag.pubads().set('page_url', '//nate.com');",
            "    googletag.setConfig({ singleRequest: true });",
            "    var _ANCHOR_INS_ID = 'gpt_unit_/21682743634,22664242840/nate/nate_mo_pan_anchor_1x1_0';",
            "    var _BOTTOM_DOWN = 'calc(30px + env(safe-area-inset-bottom))';",
            "    var anchorSlot = googletag.defineOutOfPageSlot('/21682743634,22664242840/nate/nate_mo_pan_anchor_1x1', googletag.enums.OutOfPageFormat.BOTTOM_ANCHOR);",
            "    if (anchorSlot) {",
            "       anchorSlot.setConfig({ targeting: { ad_type: 'anchor' } }).addService(googletag.pubads());",
            "       googletag.pubads().enableSingleRequest();",
            "       // 우리가 bottom을 제어하는 fixed 요소들",
            "       var _MANAGED_SELECTOR = '.floating-write, .btn_bookmark, #btn_top_float, .btn_top_float, .layer_liveTalk';",
            "       // 앵커 ins(광고) 높이",
            "       var _adHeight = function () {",
            "           var _el = document.getElementById(_ANCHOR_INS_ID) || document.querySelector('[data-anchor-status]');",
            "           return _el ? _el.offsetHeight : 0;",
            "       };",
            "       // GPT가 넣는 transform 무력화 (none으로 덮음)",
            "       var _killTransform = function (el) {",
            "           if (el && el.style.transform && el.style.transform !== 'none') el.style.transform = 'none';",
            "       };",
            "       // .layer_liveTalk: (displayed + active) 일 때만 (광고높이+30px), 그 외에는 인라인 제거(원래 CSS)",
            "       var _applyLiveTalk = function () {",
            "           var _lt = document.querySelector('.layer_liveTalk');",
            "           if (!_lt) return;",
            "           if (_uiUp && _lt.classList.contains('active')) {",
            "               _lt.style.bottom = (_adHeight() + 30) + 'px';",
            "           } else {",
            "               _lt.style.removeProperty('bottom');",
            "           }",
            "       };",
            "       // 앵커 상태에 따른 UI 위치 일괄 적용 (요소 없으면 자동 skip)",
            "       var _setUiState = function (up) {",
            "           _uiUp = up;",
            "           var _h = up ? _adHeight() : 0;",
            "           var _fw = document.querySelector('.floating-write');",
            "           if (_fw) _fw.style.bottom = up ? ('calc(' + (_h + 30) + 'px + env(safe-area-inset-bottom))') : _BOTTOM_DOWN;",
            "           var _bm = document.querySelector('.btn_bookmark');",
            "           if (_bm) _bm.style.bottom = up ? (_h + 59) + 'px' : '59px';",
            "           var _top = document.querySelector('#btn_top_float, .btn_top_float');",
            "           if (_top) _top.style.bottom = up ? (_h + 13) + 'px' : '13px';",
            "           _applyLiveTalk();",
            "       };",
            "       // 광고가 채워지는 즉시 올림 (data-anchor-status 보다 빠름)",
            "       googletag.pubads().addEventListener('slotRenderEnded', function (e) {",
            "           if (e.slot === anchorSlot && !e.isEmpty) _setUiState(true);",
            "       });",
            "       googletag.enableServices();",
            "       // 스크롤이 300px를 넘는 순간 앵커 노출",
            "       var _watch = function () {",
            "           var _onScroll = function () {",
            "               if (!_anchFlag && (window.pageYOffset || document.documentElement.scrollTop) > 300) {",
            "                   _anchFlag = true;",
            "                   googletag.display(anchorSlot);",
            "                   window.removeEventListener('scroll', _onScroll);",
            "               }",
            "           };",
            "           window.addEventListener('scroll', _onScroll);",
            "           _onScroll();",
            "       };",
            "       // status는 실제로 그 속성을 가진 요소에서 읽는다",
            "       var _getAnchorStatus = function () {",
            "           var _el = document.getElementById(_ANCHOR_INS_ID) || document.querySelector('[data-anchor-status]');",
            "           return _el ? _el.getAttribute('data-anchor-status') : null;",
            "       };",
            "       // displayed→올림 / dismissed·없음→내림 / 중간→유지",
            "       var _applyUiState = function () {",
            "           var _status = _getAnchorStatus();",
            "           if (_status === 'displayed') _setUiState(true);",
            "           else if (_status === 'dismissed' || _status === null) _setUiState(false);",
            "       };",
            "       // fixed 요소들의 transform 감시 → GPT가 넣으면 즉시 none",
            "       var _guardTransforms = function () {",
            "           var _els = document.querySelectorAll(_MANAGED_SELECTOR);",
            "           for (var i = 0; i < _els.length; i++) {",
            "               (function (el) {",
            "                   _killTransform(el);",
            "                   var _to = new MutationObserver(function () { _killTransform(el); });",
            "                   _to.observe(el, { attributes: true, attributeFilter: ['style'] });",
            "               })(_els[i]);",
            "           }",
            "       };",
            "       var _uiWatch = function () {",
            "           _applyUiState();",
            "           var _obs = new MutationObserver(function (mutations) {",
            "               for (var i = 0; i < mutations.length; i++) {",
            "                   var _m = mutations[i];",
            "                   if (_m.attributeName === 'class') {",
            "                       // .layer_liveTalk의 active 토글에만 반응",
            "                       if (_m.target.classList && _m.target.classList.contains('layer_liveTalk')) _applyLiveTalk();",
            "                   } else {",
            "                       // data-anchor-status 변화 또는 노드 추가",
            "                       _applyUiState();",
            "                   }",
            "               }",
            "           });",
            "           // body가 아니라 documentElement를 감시 → 앵커가 <body> 밖에 붙어도 잡힘",
            "           _obs.observe(document.documentElement, { childList: true, subtree: true, attributes: true, attributeFilter: ['data-anchor-status', 'class'] });",
            "       };",
            "       if (document.readyState === 'loading') {",
            "           document.addEventListener('DOMContentLoaded', function () { _watch(); _uiWatch(); _guardTransforms(); });",
            "       } else {",
            "           _watch();",
            "           _uiWatch();",
            "           _guardTransforms();",
            "       }",
            "   }",
            "});"
        ].join('\n');
        _head.appendChild(_inline);
    } catch (err) {
        console.log(err);
    }
})();